common:
  _type_: 'charuco'
  size: [10, 10]
  aruco_dict: '5X5_1000'
  square_length: 40
  marker_length: 30

  min_rows: 3
  min_points: 9

boards:
  board0:
    aruco_offset: 0

  board1:
    aruco_offset: 25

  board2:
    aruco_offset: 50



