common:
  _type_: 'charuco'
  size: [10, 10]
  aruco_dict: '5X5_1000'
  square_length: 0.040
  marker_length: 0.032

  min_rows: 3
  min_points: 9

boards:
  board0:
    aruco_offset: 0

  board1:
    aruco_offset: 50

  board2:
    aruco_offset: 100

  board3:
    aruco_offset: 150

  board4:
    aruco_offset: 200


aruco_params:
  adaptiveThreshWinSizeMax: 200
  adaptiveThreshWinSizeStep: 50